### ISSUE TITLE
3D0230a and clearence issues

### ISSUE THREAD

**Issue by PeeJay** [firepick-delta/firepick-delta#8] opened 2014-12-01 11:22 UTC
Hi Neal/Karl
I have just been assembling my arms (the ball end type) and I've had some trouble getting them to fit. 
1) The spring (3D0230a) has 2mm holes when both spring socket holders have 3mm - I pressume this is just an oversight, as it all lined up when I printed another set of springs with 3mm holes.
2) When I printed the spring socket holders there was some very slight curling along the edges, but the clearance between the spring and spring socket holders is so small that the upper spring socket holder is binding on the spring. If you look at the lower spring socket holder there is a slit that prevents this binding, so I would suggest to create something similar on the upper spring socket holder.

**Comment by FlyingLotus1983** [comment] 2014-12-01 12:52
Those catenary springs are all Karl, might want to move this issue over to his repo (https://github.com/firepick1/FPD-LooseCanon).  They may and up getting deleted from this one.  I'm still on the fence about them and having minor issues that go away with regular springs.

**Comment by firepick1** [comment] 2014-12-01 13:00
Paul,

I remember having tackled those issues in the fully 3d printed rod. I made
the spring holders 2mm to get rid of the annoying clacking caused by the
shifting of the spring pin. But I did not change the shorter rod ends
for carbon rods since I use the full 3d rods.

Are using the full 3d rods or the short rod ends?

On Monday, December 1, 2014, Neil Jansen notifications@github.com wrote:

> Those catenary springs are all Karl, might want to move this issue over to
> his repo (https://github.com/firepick1/FPD-LooseCanon). They may and up
> getting deleted from this one. I'm still on the fence about them and having
> minor issues that go away with regular springs.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/firepick-delta/firepick-delta/issues/8#issuecomment-65060479
> .

## 

Karl Lew
FIREPICK SERVICES LLC
karl@firepick.org
www.firepick.org

**Comment by PeeJay** [comment] 2014-12-01 23:50
I'm using the short rod ends. What spring pin are you using? I just assumed it was a 3mm screw. If they are not going to be a permanent solution then don't worry about it. Now that I have made them they seem rather fragile so I might just use proper springs as well.

**Comment by firepick1** [comment] 2014-12-02 01:08
Yes short rod require springs. I have enough catenary testers so no
worries. Do let us know if you have spring and interruptor collisions.
These might occur for motor plates thicker than 6mm

On Monday, December 1, 2014, PeeJay notifications@github.com wrote:

> I'm using the short rod ends. What spring pin are you using? I just
> assumed it was a 3mm screw. If they are not going to be a permanent
> solution then don't worry about it. Now that I have made them they seem
> rather fragile so I might just use proper springs as well.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/firepick-delta/firepick-delta/issues/8#issuecomment-65160441
> .

## 

Karl Lew
FIREPICK SERVICES LLC
karl@firepick.org
www.firepick.org

**Comment by FlyingLotus1983** [comment] 2015-05-30 13:36
Closing issue.  We're not using catenary springs in this repo any more (catenary springs can be found over in Karl's repo, at https://github.com/firepick1/FPD-LooseCanon )

**Closed as completed by FlyingLotus1983** 2015-05-30 13:36 UTC

**Comment by firepick1** [comment] 2015-05-30 16:06
For those of you with LooseCanon parts, I apologize for the collision. My interim solution is to use the LooseCanon optical switch interruptor, which has a rake-back angle that prevents the collision. I'll eventually address this, but am currently busy with calibration and motion as a priority.
